[package]
name = "redis-module-sys"
version = "0.1.0"
authors = ["Brandur <brandur@mutelight.org>", "dwerner <dan.werner@gmail.com>"]
build = "build.rs"

[dependencies]
bitflags = "0.8"
libc = "0.2"
time = "0.1"

[build-dependencies]
gcc = "0.3"
